spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    date-format: "yyyy-MM-dd HH:mm"
    flyway:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    #      ddl-auto: none
    #      ddl-auto: drop-and-create
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    datasource:
      url: jdbc:h2:mem:test
      username: sa
      password:
      driverClassName: org.h2.Driver
      jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

