--CREATE TABLE test.blog_post (
--  id BIGINT AUTO_INCREMENT NOT NULL,
--   name VARCHAR(255),
--   summary VARCHAR(255),
--   contents VARCHAR(255),
--   created_date TIMESTAMP,
--   modified_date TIMESTAMP,
--   created_by VARCHAR(255),
--   modified_by VARCHAR(255),
--   CONSTRAINT pk_blogpost PRIMARY KEY (id)
--);